# Generated by Django 4.0.4 on 2022-04-18 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rush', '0002_alter_post_group_alter_profile_banner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.IntegerField(choices=[(0, 'Undefined'), (1, 'Female'), (2, 'Male')], default=0),
        ),
    ]
