version: "3.9"

services:
  db:
    image: postgres:12.1
    ports:
    - "5434:5432"
    volumes:
      - ./docker/postgres:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rush
  rush-api:
    build:
      context: .
      target: DevServer
    container_name: rush-api
    ports:
      - "8000:8000"
    env_file: .env
    volumes:
      - .:/code
    stdin_open: true
    tty: true
    restart: always